In [4]:
import numpy as np
#E matrix
R = np.matrix([[-1,-1,-1,-1,0,-1],
              [-1,-1,-1,0,-1,100],
              [-1,-1,-1,0,-1,-1],
              [-1,0,0,-1,0,-1],
              [-1,0,0,-1,-1,100],
              [-1,0,-1,-1,0,100]])

In [5]:
Q=np.matrix(np.zeros([6,6]))

In [6]:
Q

matrix([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [7]:
gamma=0.8
initial_state=1

In [14]:
def available_actions(state):
  current_state_row=R[state,]
  av_act=np.where(current_state_row>=0)[1]
  return av_act

In [15]:
available_act=available_actions(initial_state)

In [16]:
available_act

array([3, 5])

In [17]:
def sample_next_action(available_actions_range):
  next_action=int(np.random.choice(available_act,1))
  return next_action

In [18]:
#Sample next action to be performed
action=sample_next_action(available_act)

In [19]:
action

5

In [24]:
#this function updates the Qmatrix according to the path selected
def update(current_state,action,gamma):
  max_index=np.where(Q[action,]==np.max(Q[action,]))[1]

  if max_index.shape[0]>1:
    max_index=int(np.random.choice(max_index,size=1))
  else:
    max_index=int(max_index)
  max_value=Q[action,max_index]

  #Q-learning fomula
  Q[current_state,action]=R[current_state,action]+gamma*max_value

#update Q matrix
update(initial_state,action,gamma)

In [25]:
Q

matrix([[  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [27]:
#Training
#Train over 10,000 iterations
for i in range(10000):
  current_state=np.random.randint(0,int(Q.shape[0]))
  available_act=available_actions(current_state)
  action=sample_next_action(available_act)
  update(current_state,action,gamma)

In [28]:
Q

matrix([[  0.,   0.,   0.,   0., 400.,   0.],
        [  0.,   0.,   0., 320.,   0., 500.],
        [  0.,   0.,   0., 320.,   0.,   0.],
        [  0., 400., 256.,   0., 400.,   0.],
        [  0., 400., 256.,   0.,   0., 500.],
        [  0., 400.,   0.,   0., 400., 500.]])

In [29]:
#normalize the trained Q-matrix
print("Trained Q matrix:")
print(Q/np.max(Q*100))

Trained Q matrix:
[[0.      0.      0.      0.      0.008   0.     ]
 [0.      0.      0.      0.0064  0.      0.01   ]
 [0.      0.      0.      0.0064  0.      0.     ]
 [0.      0.008   0.00512 0.      0.008   0.     ]
 [0.      0.008   0.00512 0.      0.      0.01   ]
 [0.      0.008   0.      0.      0.008   0.01   ]]


In [30]:
current_state=1
steps=[current_state]

while current_state !=5:
  next_step_index=np.where(Q[current_state,]==np.max(Q[current_state,]))[1]
  if next_step_index.shape[0]>1:
    next_step_index=int(np.random.choice(next_step_index,size=1))
  else:
    next_step_index=int(next_step_index)
  
  steps.append(next_step_index)
  current_state=next_step_index